[dns]
no-ipv6
server = 223.5.5.5
server = 119.29.29.29
server = 114.114.114.114
server = /*.taobao.com/223.5.5.5
server = /*.tmall.com/223.5.5.5
server = /*.alipay.com/223.5.5.5
server = /*.qq.com/119.29.29.29
server = /*.tencent.com/119.29.29.29
server = /*.bilibili.com/119.29.29.29
